// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Configuración real de Firebase para el proyecto professor-ranking-app-ulima
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcqlh_DvU3zDgS8fjxTUl1wQ9gjuIfGgE',
    appId: '1:703666102784:web:6cf1a698feb2399e8e6ee5',
    messagingSenderId: '703666102784',
    projectId: 'professor-ranking-app-ulima',
    authDomain: 'professor-ranking-app-ulima.firebaseapp.com',
    storageBucket: 'professor-ranking-app-ulima.firebasestorage.app',
    measurementId: 'G-KFVBMP61CB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcqlh_DvU3zDgS8fjxTUl1wQ9gjuIfGgE',
    appId: '1:703666102784:web:6cf1a698feb2399e8e6ee5',
    messagingSenderId: '703666102784',
    projectId: 'professor-ranking-app-ulima',
    storageBucket: 'professor-ranking-app-ulima.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcqlh_DvU3zDgS8fjxTUl1wQ9gjuIfGgE',
    appId: '1:703666102784:web:6cf1a698feb2399e8e6ee5',
    messagingSenderId: '703666102784',
    projectId: 'professor-ranking-app-ulima',
    storageBucket: 'professor-ranking-app-ulima.firebasestorage.app',
    iosClientId: 'tu-ios-client-id-aqui',
    iosBundleId: 'com.example.professorRankingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcqlh_DvU3zDgS8fjxTUl1wQ9gjuIfGgE',
    appId: '1:703666102784:web:6cf1a698feb2399e8e6ee5',
    messagingSenderId: '703666102784',
    projectId: 'professor-ranking-app-ulima',
    storageBucket: 'professor-ranking-app-ulima.firebasestorage.app',
    iosClientId: 'tu-ios-client-id-aqui',
    iosBundleId: 'com.example.professorRankingApp',
  );
} 